### PR TITLE
Use $window.googletag during init

### PR DESCRIPTION
**Pull request by CaptainCodeman**
For browserify compatibility ...

The googletag at the top of the file was being used instead of the global window.googletag that the gpt.js script creates (when the script is wrapped in a closure).

### CODE REVIEW

**Comment by ianmurrays** [comment]
Hey thanks for this. I was thinking though, wouldn't it make it easier to just inject `window` in the provider definition and use it from there?

**Comment by CaptainCodeman** [comment]
Yeah, I was being lazy and doing the least work possible to solve my problem :grinning: 

I'll update it as you suggest.

I was thinking too that the other provider methods (e.e. `refreshAds`) should also use the deferred.promise to make sure they wait for the script to load. I've noticed a couple of occasional errors that I think are to do with the timing (which the local variables were maybe there for?)

**Comment by ianmurrays** [comment]
I never ran into issues like that but they're definitely possible and perhaps avoidable by having all methods depend on the script promise. If it works, go for it :)

**Comment by ianmurrays** [comment]
Hey @CaptainCodeman I'm not sure what the status of this PR was. Could you refresh my memory?

**Comment by CaptainCodeman** [comment]
Oops, sorry about that!

It turns out the deferred approach is fundamentally wrong - the ad script isn't guaranteed to be ready when it has completed loading as it may itself load other things. This is why they have the `googletag` array that you push commands to as a queue (similar to how analytics works too).

So, the initial problem I ran into was just the scope of that when used with browserify but I then ended up making more changes to support other features I wanted but never got round to making a PR for it all. I'll try and get to it sometime soon but in the meantime this PR should probably be closed.

**Comment by ianmurrays** [comment]
Okay. Gonna close this for now. Let's reopen if necessary. ;)

**Pull request closed without merging**
