### PR TITLE
Adding refresh and timeout attributes

### PR DESCRIPTION
**Pull request by oitozero**

### CODE REVIEW

**Comment by ianmurrays** [comment]
Hey thanks for this. I think this should bump the version to 0.7.0 shouldn't it?

**Comment by oitozero** [comment]
@ianmurrays Probably, since it's an additional feature. I will submitting another PR to add support for Responsive Ads (https://github.com/ianmurrays/ngDfp/issues/2) and had already bumped that version to 0.7.0. 
Let me know if you want me to bump this to 0.7.0 and the next PR as 0.8.0?

**Comment by ianmurrays** [comment]
Let's do that, makes sense. Could you also if you have the time update the README? That'd be awesome :smile:

**Comment by oitozero** [comment]
Closing PR and submitting a cleaner PR.

**Pull request closed without merging**
