### PR TITLE
Adding googletag.cmd.push

### PR DESCRIPTION
**Pull request by oitozero**
when the GPT JavaScript is loaded, it looks through the array and executes all the functions in order

### CODE REVIEW

**Comment by oitozero** [comment]
Fix #14

**Comment by ianmurrays** [comment]
Looks good, thanks again!

**Comment by oitozero** [comment]
@ianmurrays Can you draft a new release for 0.9.0? Thanks

**Comment by ianmurrays** [comment]
Sorry, forgot about it. Done.

**Comment by oitozero** [comment]
Super quick! Awesome! :+1:

**Pull request merged**
